apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-demo-frontend-ingress
spec:
  defaultBackend:
    service:
      name: my-otel-demo-frontendproxy
      port:
        number: 8080
